# Generated by Django 3.1.3 on 2020-11-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201128_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_on',
        ),
    ]
