# Generated by Django 3.1.3 on 2020-11-28 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201128_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
