# Generated by Django 3.1.3 on 2020-11-29 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
